sonar.sources=apps
sonar.tests=apps

sonar.test.inclusions=**/*.test.ts,**/*.e2e.test.ts
sonar.exclusions=**/dist/**,**/coverage/**,**/node_modules/**,**/*.test.ts,**/*.e2e.test.ts
sonar.cpd.exclusions=**/*.test.ts,**/*.e2e.test.ts
